In [1]:
import numpy as np
import pandas as pd

In [2]:
courses_df = pd.read_csv("udemy_courses/Course_info.csv")
courses_df["id"] = courses_df["id"].astype("int64")
courses_df["num_subscribers"] = courses_df["num_subscribers"].astype("int64")
courses_df["content_length_min"] = courses_df["content_length_min"].astype("int64")

In [3]:
courses_df

id                                              title  is_paid  \
0          4715             Online Vegan Vegetarian Cooking School     True   
1          1769         The Lean Startup Talk at Stanford E-Corner    False   
2          5664  How To Become a Vegan, Vegetarian, or Flexitarian     True   
3          7723                               How to Train a Puppy     True   
4          8157                      Web Design from the Ground Up     True   
...         ...                                                ...      ...   
209729  4913954                Let's Speak Urdu - The Urdu Grammar     True   
209730  4914146  CompTIA Linux+ (XKO-004/005 # 2 Practice Exam ...     True   
209731  4914002  CISSP 4 full exams #1 : All CISSP domains - 12...     True   
209732  4913934  JD Edwards EnterpriseOne Fixed Assets Accounti...     True   
209733  4914054  CISSP 4 full exams #2 : All CISSP domains - 12...     True   

         price                                           headline  \
0        24.99  Learn to cook delicious vegan recipes. Filmed ...   
1         0.00  Debunking Myths of Entrepreneurship A startup ...   
2        19.99  Get the tools you need for a lifestyle change ...   
3       199.99  Train your puppy the right way with Dr. Ian Du...   
4       159.99  Learn web design online: Everything you need t...   
...        ...                                                ...   
209729   19.99  Urdu - Become fluent in this beautiful South A...   
209730   49.99  Practice Latest exam questions with detailed e...   
209731   49.99  Practice Latest exam questions with detailed e...   
209732  119.99  Full-length course (Part-3 of 3) on JD Edwards...   
209733   49.99  Practice Latest exam questions with detailed e...   

        num_subscribers  avg_rating  num_reviews  num_comments  num_lectures  \
0                  2231        3.75        134.0          42.0          37.0   
1                 26474        4.50        709.0         112.0           9.0   
2                  1713        4.40         41.0          13.0          14.0   
3                  4988        4.80        395.0          88.0          36.0   
4                  1266        4.75         38.0          12.0          38.0   
...                 ...         ...          ...           ...           ...   
209729                3        0.00          0.0           0.0           5.0   
209730                0        0.00          0.0           0.0           0.0   
209731                0        0.00          0.0           0.0           0.0   
209732                0        0.00          0.0           0.0           9.0   
209733                0        0.00          0.0           0.0           0.0   

        content_length_min        published_time last_update_date  \
0                     1268  2010-08-05T22:06:13Z       2020-11-06   
1                       88  2010-01-12T18:09:46Z              NaN   
2                       82  2010-10-13T18:07:17Z       2019-10-09   
3                     1511  2011-06-20T20:08:38Z       2016-01-13   
4                      569  2011-06-23T18:31:20Z              NaN   
...                    ...                   ...              ...   
209729                  54  2022-10-05T11:31:36Z       2022-10-06   
209730                   0  2022-10-05T12:29:23Z       2022-10-05   
209731                   0  2022-10-05T11:04:05Z       2022-10-05   
209732                  82  2022-10-05T10:30:19Z       2022-10-05   
209733                   0  2022-10-05T11:36:34Z       2022-10-05   

                    category                 subcategory  \
0                  Lifestyle             Food & Beverage   
1                   Business            Entrepreneurship   
2                  Lifestyle             Other Lifestyle   
3                  Lifestyle         Pet Care & Training   
4                     Design                  Web Design   
...                      ...                         ...   
209729  Teaching & Academ

In [4]:
def print_course_info(course_id, i):
    print("-"*40);
    if i == 0:
        print("----------TAKEN COURSE----------")
    elif i == 1:
        print("----------TOP RECOMMENDED COURSE----------")
    else:
        print("----------OTHER RECCOMMENDATIONS----------")
    print("-"*40);
    print("Course ID: {}".format(list(courses_df[courses_df["id"]==course_id]["id"])))
    print("Recommended Course: {}".format(list(courses_df[courses_df["id"]==course_id]["title"])))
    print("Instructor Name: {}".format(list(courses_df[courses_df["id"]==course_id]["instructor_name"])))
    print("Category: {}".format(list(courses_df[courses_df["id"]==course_id]["category"])))
    print("Sub-category: {}".format(list(courses_df[courses_df["id"]==course_id]["subcategory"])))
    print("Topic: {}".format(list(courses_df[courses_df["id"]==course_id]["topic"])))
    print("Number of Subscribers: {}".format(list(courses_df[courses_df["id"]==course_id]["num_subscribers"])))
    print("Average Rating: {}".format(list(courses_df[courses_df["id"]==course_id]["avg_rating"])))
    print("Content Length(min): {}".format(list(courses_df[courses_df["id"]==course_id]["content_length_min"])))
    print("Language: {}".format(list(courses_df[courses_df["id"]==course_id]["language"])))
    print("Price: {}".format(list(courses_df[courses_df["id"]==course_id]["price"])))
    print("-"*40)

In [5]:
df = pd.read_csv("udemy_courses/reviews_cleaned.csv")
table = pd.pivot_table(df, values="rate", columns="user_id", index="course_id").fillna(0)
table

user_id    0      1      2      3      4      5      6      7      8      \
course_id                                                                  
9711         0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10812        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
11331        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
13034        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
15639        0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
3982816      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4049392      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4189168      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4359576      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4599580      0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

user_id    9      ...  59667  59668  59669  59670  59671  59672  59673  59674  \
course_id         ...                                                           
9711         0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
10812        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
11331        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
13034        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
15639        0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
...          ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
3982816      0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4049392      0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4189168      0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4359576      0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4599580      0.0  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

user_id    59675  59676  
course_id                
9711         0.0    0.0  
10812        0.0    0.0  
11331        0.0    0.0  
13034        0.0    0.0  
15639        0.0    0.0  
...          ...    ...  
3982816      0.0    0.0  
4049392      0.0    0.0  
4189168      0.0    0.0  
4359576      0.0    0.0  
4599580      0.0    0.0  

[1030 rows x 59677 columns]

In [6]:
from scipy.sparse import csr_matrix

In [7]:
matrix = csr_matrix(table.values)

In [8]:
from sklearn.neighbors import NearestNeighbors

In [9]:
knn = NearestNeighbors(metric = "cosine")
knn.fit(matrix)

NearestNeighbors(metric='cosine')

In [10]:
course = np.random.choice(table.shape[0])

In [11]:
dist, ind = knn.kneighbors(table.iloc[course].values.reshape(1, -1), n_neighbors=6)

In [12]:
dist

array([[4.55191440e-15, 8.73268596e-01, 9.32308810e-01, 9.36957436e-01,
        9.42521879e-01, 9.45874297e-01]])

In [13]:
ind

array([[366, 592, 707,  95, 321, 575]], dtype=int64)

In [14]:
ind.flatten()

array([366, 592, 707,  95, 321, 575], dtype=int64)

In [15]:
for i in range(len(dist.flatten())):
    if i == 0:
        print_course_info(table.index[course], 0)
    else:
        print_course_info(table.index[ind.flatten()[i]], i)

----------------------------------------
----------TAKEN COURSE----------
----------------------------------------
Course ID: [922484]
Recommended Course: ['The Complete Node.js Developer Course (3rd Edition)']
Instructor Name: ['Andrew Mead']
Category: ['Development']
Sub-category: ['Programming Languages']
Topic: ['Node.Js']
Number of Subscribers: [282270]
Average Rating: [4.6403704]
Content Length(min): [2103]
Language: ['English']
Price: [84.99]
----------------------------------------
----------------------------------------
----------TOP RECOMMENDED COURSE----------
----------------------------------------
Course ID: [1286908]
Recommended Course: ['The Complete React Developer Course (w/ Hooks and Redux)']
Instructor Name: ['Andrew Mead']
Category: ['Development']
Sub-category: ['Web Development']
Topic: ['React JS']
Number of Subscribers: [81239]
Average Rating: [4.54]
Content Length(min): [2352]
Language: ['English']
Price: [99.99]
----------------------------------------
-----

In [16]:
from sklearn.decomposition import TruncatedSVD

In [17]:
svd = TruncatedSVD(n_components=12, random_state=1)
svd_matrix = svd.fit_transform(table.values)

In [18]:
svd_matrix

array([[ 0.82223162,  0.06352465,  0.09603219, ...,  0.50321866,
         0.17768588, -0.03502864],
       [ 0.8850403 , -0.16089569,  0.04336191, ..., -0.33322021,
         0.38583387, -0.11332821],
       [ 0.88138847, -0.39111023,  0.21389642, ...,  0.2667585 ,
         0.36566565, -0.16639389],
       ...,
       [ 0.47272258, -0.32659868, -0.1733398 , ...,  0.14054314,
         0.10906289,  0.06051385],
       [ 0.87560974, -0.13022685, -0.09831357, ..., -0.07929232,
        -0.05112202, -0.04680784],
       [ 0.25433412, -0.16996205, -0.01652945, ..., -0.14055318,
         0.04708424,  0.11532716]])

In [19]:
import warnings
warnings.filterwarnings("ignore")

In [20]:
corr = np.corrcoef(svd_matrix)

In [21]:
course

366

In [22]:
courses = list(table.index)
courses[course]

922484

In [23]:
courses

[9711,
 10812,
 11331,
 13034,
 15639,
 21386,
 22169,
 24823,
 26433,
 41295,
 42271,
 43718,
 48841,
 49250,
 53600,
 53670,
 58207,
 59527,
 60346,
 65330,
 74092,
 80940,
 81372,
 83464,
 95246,
 97280,
 101866,
 110240,
 118042,
 120058,
 120600,
 130064,
 133536,
 139166,
 139200,
 146156,
 151198,
 151668,
 164058,
 171838,
 173548,
 180806,
 192004,
 196152,
 201966,
 203556,
 214008,
 217000,
 218794,
 219776,
 221578,
 221674,
 221696,
 225796,
 236676,
 238934,
 245880,
 246154,
 246314,
 246392,
 246652,
 247190,
 256758,
 257626,
 258316,
 260284,
 269394,
 271228,
 274556,
 277654,
 280332,
 285934,
 288620,
 289230,
 291766,
 293170,
 299398,
 299618,
 308690,
 311538,
 313360,
 314462,
 321410,
 328386,
 331738,
 333610,
 335610,
 341182,
 348116,
 352440,
 354176,
 355212,
 356030,
 358540,
 362632,
 364426,
 366280,
 371090,
 378726,
 380872,
 382002,
 382966,
 383576,
 384496,
 387820,
 393268,
 396876,
 397068,
 399938,
 403314,
 404944,
 405252,
 405282,
 405818,
 

In [24]:
indices = [i for i, x in enumerate(list(corr[course]>0.90)) if x == True]
indices

[73,
 95,
 131,
 150,
 163,
 236,
 261,
 272,
 289,
 313,
 322,
 331,
 366,
 381,
 395,
 420,
 476,
 567,
 572,
 575,
 592,
 606,
 620,
 651,
 670,
 688,
 698,
 716,
 743,
 774,
 798,
 842,
 845,
 946,
 971]

In [25]:
corrs={}
for j in indices:
    corrs.update({j:list(corr[course])[j]})

In [26]:
corr_dict = dict(reversed(sorted(corrs.items(), key=lambda item: item[1])))

In [27]:
list(corr_dict)[:6]

[366, 567, 592, 395, 331, 575]

In [28]:
top_5 = [courses[index] for index in list(corr_dict)[:6]]
top_5

[922484, 1241254, 1286908, 959700, 861624, 1254420]

In [29]:
for i in range(len(top_5)):
    if i == 0:
        print_course_info(top_5[i], 0)
    else:
        print_course_info(top_5[i], i)

----------------------------------------
----------TAKEN COURSE----------
----------------------------------------
Course ID: [922484]
Recommended Course: ['The Complete Node.js Developer Course (3rd Edition)']
Instructor Name: ['Andrew Mead']
Category: ['Development']
Sub-category: ['Programming Languages']
Topic: ['Node.Js']
Number of Subscribers: [282270]
Average Rating: [4.6403704]
Content Length(min): [2103]
Language: ['English']
Price: [84.99]
----------------------------------------
----------------------------------------
----------TOP RECOMMENDED COURSE----------
----------------------------------------
Course ID: [1241254]
Recommended Course: ['AWS Serverless APIs & Apps - A Complete Introduction']
Instructor Name: ['Academind by Maximilian Schwarzmüller']
Category: ['Development']
Sub-category: ['Web Development']
Topic: ['Amazon AWS']
Number of Subscribers: [78617]
Average Rating: [4.648148]
Content Length(min): [472]
Language: ['English']
Price: [139.99]
------------------